### ISSUE TITLE
cudaCheckError() failed : no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by kongyan66** [ChrisAllenMing/GPA-detection#23]
when i run train ,i occured a problem,as follow:
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
cudaCheckError() failed : no kernel image is available for execution on the device

I used the environment configuration provided by the author, so i don't know how to solve it, looking forward to your relpy,thanks!

**Comment by drickzsy** [comment]
Hi, sorry to bother you! Have you solved this problem?

**Comment by kongyan66** [comment]
@drickzsy    yes,  when i use cuda9.0 to make.sh  again, this problem is solved. Although it also happen,the code can run normally. So i think the version of GPU and CUDA is very important.

my detail of make.sh as follows:
export CUDA_PATH=/usr/local/cuda-9.0/
#You may also want to ad the following
#export C_INCLUDE_PATH=/opt/cuda/include


export CXXFLAGS="-std=c++11"
export CFLAGS="-std=c99"
export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
export CPATH=/usr/local/cuda-9.0/include${CPATH:+:${CPATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

python setup.py build_ext --inplace
rm -rf build
CUDA_ARCH = "-gencode arch=compute_30,code=sm_30 \
           -gencode arch=compute_35,code=sm_35 \
           -gencode arch=compute_50,code=sm_50 \
           -gencode arch=compute_52,code=sm_52 \
           -gencode arch=compute_60,code=sm_60 \
           -gencode arch=compute_61,code=sm_61 \
           -gencode arch=compute_62,code=sm_62 "
.......
hope to help you!

**Comment by drickzsy** [comment]
> @drickzsy yes, when i use cuda9.0 to make.sh again, this problem is solved. So i think the version of GPU and CUDA is very important.
> 
> my detail of make.sh as follows:
> export CUDA_PATH=/usr/local/cuda-9.0/
> #You may also want to ad the following
> #export C_INCLUDE_PATH=/opt/cuda/include
> 
> export CXXFLAGS="-std=c++11"
> export CFLAGS="-std=c99"
> export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
> export CPATH=/usr/local/cuda-9.0/include${CPATH:+:${CPATH}}
> export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
> 
> python setup.py build_ext --inplace
> rm -rf build
> CUDA_ARCH = "-gencode arch=compute_30,code=sm_30
> -gencode arch=compute_35,code=sm_35
> -gencode arch=compute_50,code=sm_50
> -gencode arch=compute_52,code=sm_52
> -gencode arch=compute_60,code=sm_60
> -gencode arch=compute_61,code=sm_61
> -gencode arch=compute_62,code=sm_62 "
> .......
> hope to help you!

Thank you!  Which model of your server's graphics card? And what's your anaconda?

**Comment by kongyan66** [comment]
@drickzsy   2080s and python 3.6
conda list as fllows:
<html>
<body>


_libgcc_mutex | 0.1 |  
-- | -- | --
_openmp_mutex | 4.5 |  
certifi | 2016.2.28 |  
cffi | 1.10.0 |  
cuda100 | 1.0 |  
cycler | 0.10.0 |  
cython | 0.26 |  
easydict | 1.9 |  
freetype | 2.5.5 |  
jbig | 2.1 |  
jpeg | 9b |  
kiwisolver | 1.3.1 |  
libblas | 3.9.0 |  
libcblas | 3.9.0 |  
libffi | 3.2.1 |  
libgcc-ng | 9.3.0 |  
libgfortran-ng | 9.3.0 |  
libgfortran5 | 9.3.0 |  
liblapack | 3.9.0 |  
libopenblas | 0.3.15 |  
libpng | 1.6.30 |  
libstdcxx-ng | 9.3.0 |  
libtiff | 4.0.6 |  
llvm-openmp | 11.1.0 |  
matplotlib | 3.3.4 |  
mkl | 2021.2.0 |  
msgpack | 1.0.2 |  
ninja | 1.7.2 |  
numpy | 1.19.5 |  
olefile | 0.44 |  
opencv-python | 4.5.2.54 |  
openssl | 1.0.2l |  
pillow | 8.2.0 |  
pip | 21.1.2 |  
protobuf | 3.17.3 |  
pycparser | 2.18 |  
pyparsing | 2.4.7 |  
python | 3.6.2 |  
python-dateutil | 2.8.1 |  
python_abi | 3.6 |  
pytorch | 0.4.1 |  
pyyaml | 5.4.1 |  
readline | 6.2 |  
scipy | 1.2.0 |  
setuptools | 36.4.0 |  
six | 1.10.0 |  
sqlite | 3.13.0 |  
tbb | 2021.2.0 |  
tensorboardx | 2.2 |  
tk | 8.5.18 |  


</body>
</html>
